### ISSUE TITLE
Change environment variables

### ISSUE THREAD

**Issue by colearendt** [tbradley1013/connectAnalytics#10]
Apologies for the flip-flop, but we recently changed our default environment variables from the `RSTUDIO_CONNECT_*` to `CONNECT_*`. We did this across the board (as we had several competing standards emerging). As a result, I think it would be best / easiest if you can also switch to use those defaults 😄

i.e.
```
RSTUDIO_CONNECT_SERVER -> CONNECT_SERVER
RSTUDIO_CONNECT_API_KEY -> CONNECT_API_KEY
```

**Comment by tbradley1013** [comment]
https://github.com/tbradley1013/connectAnalytics/commit/c3c2679406fe796744967645a6890083f5910650 takes care of this
