### ISSUE TITLE
Require newer version of `tidyr`

### ISSUE THREAD

**Issue by colearendt** [tbradley1013/connectAnalytics#11]
https://github.com/tbradley1013/connectAnalytics/blob/8ad2c7d86e8dd7b52f8385d0c28e79404aea9d8d/DESCRIPTION#L26

I'm not sure when this function became available, but you may need a version restriction on `tidyr`:
```
Warning: Error in : 'pivot_longer' is not an exported object from 'namespace:tidyr'
```

**Comment by tbradley1013** [comment]
Looks like v1.0.0 is when it was introduced in the changelog so I will require that. If you think that is a potential issue, I am happy to revert back to `spread`/`gather`. 
https://github.com/tbradley1013/connectAnalytics/commit/c3c2679406fe796744967645a6890083f5910650  updates version restriction for `tidyr`

**Comment by colearendt** [comment]
Oh not at all! 😄 Just something to help users ensure they have the updated versions. Awesome!
