### ISSUE TITLE
feature request - downloadable table of access

### ISSUE THREAD

**Issue by iainmwallace** [tbradley1013/connectAnalytics#13]
Hi,

This is such an awesome package, thanks for developing it.

Three small suggestions
- enable filtering of graphs to exclude removed content + the publisher themselves
- a table displaying all the access details for each shiny/static reports 
e.g. fields would be
Shiny app name
User
Access time 
- display information about pins also (https://github.com/rstudio/pins) 

Cheers,

Iain

**Comment by tbradley1013** [comment]
When you say 

> enable filtering of graphs to exclude removed content + the publisher themselves

I assume you mean on the admin tab? 

As far as the information about pins: The ability to implement that is dependent on the [`connectapi`](https://github.com/rstudio/connectapi) package and more importantly the Connect API exposing that data. AFAIK, pin usage is not exposed in the current API. Given the relative newness of pins, I would guess it will be something they plan to implement, but I don't have any information supporting that assumption. 

The other two things (or three if I include the title request) shouldn't be much of an issue to add. Thanks for filing the issue

**Comment by tbradley1013** [comment]
I implemented your first two requests with PR #14 , which has been merged into the master branch. You can install the updated version  now using:

```
devtools::install_github("tbradley1013/connectAnalytics")
```

I am going to close this. If you would like to see the pins implemented, you should first file a feature request over at the `connectapi` package, as that is the official api package being developed by RStudio. 

Please open more issues if you have any more feature requests or find any bugs!

**Comment by iainmwallace** [comment]
Fantastic, thanks!

**Comment by iainmwallace** [comment]
Just checked it out and it looks great. 

A small thought would be to enable column filters on the content table (similar to DT column filters, https://rstudio.github.io/DT/)- this would make it very easy to check if person x has looked at the report since I e-mailed it

**Comment by tbradley1013** [comment]
Oh I meant to add that and forgot. I have added the ability to filter all columns and sort any columns. I also added the times to the started and ended column that I mistakenly left out. 

Thanks
