### ISSUE TITLE
Feature request - display access stats for pins

### ISSUE THREAD

**Issue by iainmwallace** [tbradley1013/connectAnalytics#15]
Hi,

Pins are displayed in the "User tab" as an application, with content category "pin". 
They don't seem to appear in any of the reports though.

Thanks

Iain

**Comment by tbradley1013** [comment]
Can you share the output of the following (remove anything sensitive):

```
library(connectapi)
tmp <- connectapi::connect()
connectapi::get_usage_static(
     tmp ,
      content_guid = '<your-pin-guid>',
      limit = Inf
    )
```

I can't think of anything that would be causing the pins to be filtered out of the usage data in the application if they are appearing in the usage report from these functions

**Comment by iainmwallace** [comment]
Sure - this is what it looks like for a random pin of mine
``` r
structure(list(content_guid = c("f505fb7c-3fd9-4082-9a1d-f009e3a317e8", 
"f505fb7c-3fd9-4082-9a1d-f009e3a317e8"), user_guid = c("fbd09db2-01e4-4b8e-93a8-e93d8fb5e827", 
"fbd09db2-01e4-4b8e-93a8-e93d8fb5e827"), variant_key = c(NA_character_, 
NA_character_), time = structure(c(1582772284, 1582831797), class = c("POSIXct", 
"POSIXt"), tzone = ""), rendering_id = c(NA_character_, NA_character_
), bundle_id = c("1295", "1295"), data_version = c(1L, 1L)), row.names = c(NA, 
-2L), class = c("tbl_df", "tbl", "data.frame"))
#>                           content_guid                            user_guid
#> 1 f505fb7c-3fd9-4082-9a1d-f009e3a317e8 fbd09db2-01e4-4b8e-93a8-e93d8fb5e827
#> 2 f505fb7c-3fd9-4082-9a1d-f009e3a317e8 fbd09db2-01e4-4b8e-93a8-e93d8fb5e827
#>   variant_key                time rendering_id bundle_id data_version
#> 1        <NA> 2020-02-26 21:58:04         <NA>      1295            1
#> 2        <NA> 2020-02-27 14:29:57         <NA>      1295            1
```

<sup>Created on 2020-03-05 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by tbradley1013** [comment]
Ok. I figure out what was happening. pins appear to not have a title associated with them which was resulting them getting labeled as "Removed Content". I have made a change that if a piece of content does not have a title, it will use the content name as the title and if it has neither it will be marked as "Removed Content"

This has been pushed to the master branch and should fix the issue.

**Comment by iainmwallace** [comment]
Works for me! Thanks for the quick fix :)
